import turtle

donatello = turtle.Turtle()
win = turtle.Screen()
win.bgcolor("#89cff0")
donatello.penup()
turtle.setup(800, 800)
donatello.pencolor('green')
donatello.speed(4)
donatello.pensize(200)
donatello.setpos(-400,-400)
donatello.pendown()
donatello.forward(1000)
donatello.penup()
donatello.setposition(300,300)
donatello.pencolor('yellow')
donatello.pendown()
donatello.forward(1)
donatello.penup()
donatello.pencolor('black')
donatello.pensize(40)
donatello.setposition(260,335)
donatello.pendown()
donatello.forward(1)
donatello.penup()
donatello.setposition(340,335)
donatello.pendown()
donatello.backward(1)
donatello.penup()
donatello.pensize(20)
donatello.setpos(300,245)
donatello.pendown()
donatello.circle(75,70)
donatello.penup()
donatello.setheading(180)
donatello.setpos(300,245)
donatello.pendown()
donatello.circle(-75,70)



win.exitonclick()
